src/Entity/Actor.php
<?php

namespace App\Entity;

use App\Repository\ActorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: ActorRepository::class)]
#[Broadcast]
class Actor
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $actor_picture = null;

    #[ORM\Column(length: 255)]
    private ?string $actor_name = null;

    #[ORM\ManyToMany(targetEntity: Movie::class, inversedBy: 'actors')]
    private Collection $movies;

    public function __construct()
    {
        $this->movies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getActorPicture(): ?string
    {
        return $this->actor_picture;
    }

    public function setActorPicture(?string $actor_picture): static
    {
        $this->actor_picture = $actor_picture;

        return $this;
    }

    public function getActorName(): ?string
    {
        return $this->actor_name;
    }

    public function setActorName(string $actor_name): static
    {
        $this->actor_name = $actor_name;

        return $this;
    }

    /**
     * @return Collection<int, Movie>
     */
    public function getMovies(): Collection
    {
        return $this->movies;
    }

    public function addMovie(Movie $movie): static
    {
        if (!$this->movies->contains($movie)) {
            $this->movies->add($movie);
        }

        return $this;
    }

    public function removeMovie(Movie $movie): static
    {
        $this->movies->removeElement($movie);

        return $this;
    }


        // ! pour le CRUD dans EasyAdmin
        public function __toString()
        {
            return $this->getActorName();
            // return $this->getActorPicture();
        }
}

src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
#[Broadcast]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $category_name = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Movie::class)]
    private Collection $movies;

    public function __construct()
    {
        $this->movies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoryName(): ?string
    {
        return $this->category_name;
    }

    public function setCategoryName(string $category_name): static
    {
        $this->category_name = $category_name;

        return $this;
    }

    /**
     * @return Collection<int, Movie>
     */
    public function getMovies(): Collection
    {
        return $this->movies;
    }

    public function addMovie(Movie $movie): static
    {
        if (!$this->movies->contains($movie)) {
            $this->movies->add($movie);
            $movie->setCategory($this);
        }

        return $this;
    }

    public function removeMovie(Movie $movie): static
    {
        if ($this->movies->removeElement($movie)) {
            // set the owning side to null (unless already changed)
            if ($movie->getCategory() === $this) {
                $movie->setCategory(null);
            }
        }

        return $this;
    }



    // ! pour le CRUD dans EasyAdmin
    public function __toString()
    {
        return $this->getCategoryName();
    }
}

src/Entity/Movie.php
<?php

namespace App\Entity;

use App\Repository\MovieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

#[ORM\Entity(repositoryClass: MovieRepository::class)]
#[Vich\Uploadable]
#[Broadcast]
class Movie
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type:'string', length: 255, nullable: true)]
    private ?string $picture = null;

    #[Vich\UploadableField(mapping: 'products', fileNameProperty: 'picture')]
    private ?File $pictureFile = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 50)]
    private ?string $duration = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $release_date = null;

    #[ORM\Column]
    private ?float $review = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $synopsis = null;

    #[ORM\Column(length: 255)]
    private ?string $trailer = null;

    #[ORM\ManyToOne(inversedBy: 'movies')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\ManyToMany(targetEntity: Actor::class, mappedBy: 'movies')]
    private Collection $actors;

    public function __construct()
    {
        $this->actors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPictureFile(): ?File
    {
        return $this->pictureFile;
    }

    public function setPictureFile(?File $pictureFile = null)
    {
        $this->pictureFile = $pictureFile;

        return $this;
        // if (null !== $pictureFile) {
        //     $this->updated_at = new \DateTimeImmutable();
        // }
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDuration(): ?string
    {
        return $this->duration;
    }

    public function setDuration(string $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTimeInterface $release_date): static
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getReview(): ?float
    {
        return $this->review;
    }

    public function setReview(float $review): static
    {
        $this->review = $review;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): static
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getTrailer(): ?string
    {
        return $this->trailer;
    }

    public function setTrailer(string $trailer): static
    {
        $this->trailer = $trailer;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Actor>
     */
    public function getActors(): Collection
    {
        return $this->actors;
    }

    public function addActor(Actor $actor): static
    {
        if (!$this->actors->contains($actor)) {
            $this->actors->add($actor);
            $actor->addMovie($this);
        }

        return $this;
    }

    public function removeActor(Actor $actor): static
    {
        if ($this->actors->removeElement($actor)) {
            $actor->removeMovie($this);
        }

        return $this;
    }

}

src/Controller/MovieController.php
<?php

namespace App\Controller;

use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Movie;



class MovieController extends AbstractController
{
    // ! home page
    #[Route('/', name: 'app_movie')]
    public function index(ManagerRegistry $mr): Response // ManagerRegistry $mr pour récupérer les données avec getRepository et findAll
    {
        $subtitle = 'Les supers films de La Manu';

        $movies = $mr->getRepository(Movie::class)->findAll();

        return $this->render('movie/index.html.twig', [
            'controller_name' => 'MovieController',
            'subtitle' => $subtitle,
            'movies' => $movies,

        ]);
    }

    // ! page détail
    #[Route('/movie/detailmovie.html.twig', name: 'detail_movie')]
    public function detail(ManagerRegistry $mr): Response // ManagerRegistry $mr pour récupérer les données avec getRepository et findAll
    {
        $page = intval(filter_input(INPUT_GET, 'id', FILTER_SANITIZE_NUMBER_INT));

        $movie = $mr->getRepository(Movie::class)->find($page);

        return $this->render('movie/detailmovie.html.twig', [
            'controller_name' => 'MovieController',
            'movie' => $movie
        ]);
    }
}

templates/movie/detailmovie.html.twig
{% extends 'base.html.twig' %}


{% block title %}Accueil | Darling's Movie
{% endblock %}

{% block body %}



<section class="section__detail">
    <div class="container">
        <div class="row pt-5">
            <div class="d-flex justify-content-center flex-wrap">
                <h1 class="w-100 text-center"> {{ movie.name }} </h1>
                <hr class="title__hr">
            </div>
        </div>
        <div class="row pt-5">
            <div class="col text-center">
                <iframe width="560" height="315" src="{{ movie.trailer }}" title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    allowfullscreen></iframe>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <h2>Acteurs :</h2>
            </div>
        </div>
        <div class="row pb-5">
            {% for actor in movie.actors %}
            <div class="col-2">
                <div class="card">
                    <img src="{{ asset('img/' ~ actor.actorPicture) }}" class="card-img-top" alt="photo acteur">
                    <div class="card-body">
                        <p class="card-text">{{ actor.actorName }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>



</section>
{% endblock %}

templates/movie/index.html.twig
{% extends 'base.html.twig' %}


{% block title %}Accueil | Darling's Movie
{% endblock %}

{% block body %}


<section>
	<div class="parent">
		<div class="div1">
			<div class="back__h1">
				<h1>
					<span>DARLING,</span>
					WHAT ARE WE WATCHING TONIGHT
					<span>?</span>
				</h1>
			</div>
			<div class="main__h1">
				<h1>
					<span>CHÉRI(E),</span>
					QU’EST QU’ON REGARDE CE SOIR
					<span id="h1__question">?</span>
				</h1>
			</div>
		</div>
		<div class="div2 d-flex justify-content-center align-items-center">
			<button class="carousel__btn--left" aria-label="Bouton précédent">
				<span class="visually-hidden">Bouton précédent</span>
				<i class="bi bi-arrow-left"></i>
			</button>
		</div>
		<div class="div3 d-flex justify-content-center align-items-center">
			<button class="carousel__btn--right" aria-label="Bouton suivant">
				<span class="visually-hidden">Bouton suivant</span>
				<i class="bi bi-arrow-right"></i>
			</button>
		</div>
		{# ! dynamique #}
		{% for movie in movies %}
		<div class="div4 d-flex" data-status="{{ loop.first ? 'active' : 'inactive' }}" id="movie{{ loop.index }}"> 
			{# loop.first est une variable fournie par Twig qui indique si c'est le premier tour de la boucle. #}
			{# id="movie{{ loop.index }}" : Cela attribue un identifiant unique à chaque film en utilisant le numéro de l'itération. #}
			<div class="main__picture w-25">
				<img class="main__picture--film pt-5" src="{{ 'img/' ~ movie.picture }}" alt="photo film">
				<div class="main__review">
					{{ movie.review }}
				</div>
			</div>
			<div class="main__film w-75 px-2">
				<div class="main__film--title">
					<h2> {{ movie.name }} </h2>
				</div>
				<div class="main__film--infos d-flex">
					<div class="genre px-5">
						<p>{{ movie.category.categoryName }}</p>
					</div>
					<div class="duree px-5">
						<p>{{ movie.duration }}</p>
					</div>
					<div class="date px-5">
						<p>{{ movie.releaseDate|date('m-Y') }}</p>
					</div>
				</div>
				<div class="main__film--text">
					<p class="synopsis">
						{{ movie.synopsis|striptags }}
					</p>
				</div>
				<div class="main__film--btn">
					<a class="btn btn-light" href="{{ path('detail_movie', {'id': movie.id}) }}" target="_blank">En savoir +</a>
				</div>
			</div>
		</div>
		{% endfor %}


	</section>
{% endblock %}